"""Conservative GROMACS input preparation."""
from __future__ import annotations

from pathlib import Path
from ase.io import read, write
from molsim_agent.safety.policies import Workspace
from molsim_agent.science.models import ParameterValue, ScientificPlan
from molsim_agent.tools.registry import ToolSpec


def prepare_gromacs_md_inputs(workspace: Workspace, source: str = "POSCAR",
                              temperature_K: float = 300.0, duration_ps: float = 1.0,
                              timestep_fs: float = 1.0, ensemble: str = "nvt",
                              overwrite: bool = False) -> dict[str, object]:
    """Write geometry and reviewable MD/topology templates, never a force field."""
    if temperature_K <= 0 or duration_ps <= 0 or timestep_fs <= 0:
        raise ValueError("temperature, duration, and timestep must be positive")
    ensemble = ensemble.lower()
    if ensemble not in {"nvt", "nve"}:
        raise ValueError("ensemble must be nvt or nve")
    source_path = workspace.resolve(source, must_exist=True)
    if not source_path.is_file():
        raise ValueError(f"Not a file: {source}")
    source_format = "vasp" if source_path.name.upper() in {"POSCAR", "CONTCAR"} else None
    atoms = read(source_path, format=source_format)
    steps = round(duration_ps * 1000.0 / timestep_fs)
    output_dir = workspace.root / "outputs"
    output_dir.mkdir(parents=True, exist_ok=True)
    gro = _target(output_dir / f"{source_path.name}.gro", overwrite)
    mdp = _target(output_dir / "md.mdp", overwrite)
    topology = _target(output_dir / "topol.top.template", overwrite)
    write(gro, atoms, format="gromacs")
    thermostat = "" if ensemble == "nve" else "tc-grps                   System\nref-t                     300\ntau-t                     1.0\n"
    mdp.write_text(
        "; Generated by molsim-agent; review before production use\n"
        f"; Geometry: {workspace.relative(source_path)}\n"
        "integrator                md\n"
        f"dt                        {timestep_fs / 1000.0:g}\n"
        f"nsteps                    {steps}\n"
        "cutoff-scheme             Verlet\n"
        + ("ref-t                     300\n" if ensemble == "nvt" else "")
        + thermostat,
        encoding="utf-8",
    )
    topology.write_text(
        "; TEMPLATE ONLY - not a valid production topology.\n"
        "; Choose a force field and define atom types, charges, bonds, angles, and dihedrals.\n"
        "; POSCAR contains geometry but not this chemical information.\n",
        encoding="utf-8",
    )
    plan = ScientificPlan(
        task="GROMACS MD input preparation", code="gromacs",
        parameters=[
            ParameterValue("temperature_K", temperature_K, "default" if temperature_K == 300 else "user", True),
            ParameterValue("duration_ps", duration_ps, "default" if duration_ps == 1 else "user", True),
            ParameterValue("timestep_fs", timestep_fs, "default" if timestep_fs == 1 else "user", True),
            ParameterValue("ensemble", ensemble, "default" if ensemble == "nvt" else "user", True),
            ParameterValue("steps", steps, "derived", True),
        ],
        missing_inputs=["force field", "atom types", "charges", "topology", "gmx executable"],
        artifacts=[workspace.relative(gro), workspace.relative(mdp), workspace.relative(topology)],
    )
    return {
        "ok": True,
        "created_files": [workspace.relative(gro), workspace.relative(mdp), workspace.relative(topology)],
        "source": workspace.relative(source_path), "geometry": workspace.relative(gro),
        "mdp": workspace.relative(mdp), "topology_template": workspace.relative(topology),
        "scientific_plan": plan.to_dict(),
        "warnings": [
            "The .gro geometry was generated deterministically with ASE.",
            "md.mdp contains generic defaults and requires review.",
            "topol.top.template is intentionally incomplete; no force field or charges were invented.",
            "Do not run gmx grompp until topology and force field are supplied and validated.",
        ],
    }


def _target(path: Path, overwrite: bool) -> Path:
    if overwrite or not path.exists():
        return path
    index = 1
    while True:
        candidate = path.with_name(f"{path.stem}_{index}{path.suffix}")
        if not candidate.exists():
            return candidate
        index += 1


def gromacs_tool_specs(workspace: Workspace) -> list[ToolSpec]:
    return [ToolSpec(
        "prepare_gromacs_md_inputs",
        "Prepare an ASE GROMACS geometry and conservative MD/topology templates; never invents a force field.",
        {"type": "object", "properties": {
            "source": {"type": "string"}, "temperature_K": {"type": "number"},
            "duration_ps": {"type": "number"}, "timestep_fs": {"type": "number"},
            "ensemble": {"type": "string", "enum": ["nvt", "nve"]}, "overwrite": {"type": "boolean"},
        }, "required": ["source"], "additionalProperties": False},
        lambda source="POSCAR", temperature_K=300.0, duration_ps=1.0, timestep_fs=1.0, ensemble="nvt", overwrite=False:
            prepare_gromacs_md_inputs(workspace, source, temperature_K, duration_ps, timestep_fs, ensemble, overwrite),
        {"filesystem": "write", "workspace_only": True}, category="simulation", risk="write",
        requirements=("ase", "gmx"), compute_cost="trivial", deterministic=True,
    )]
