"""Conservative LAMMPS MD template preparation.

The structure data file is deterministic; force-field semantics are not invented.
"""
from __future__ import annotations

from molsim_agent.safety.policies import Workspace
from molsim_agent.tools.convert import convert_structure
from molsim_agent.tools.registry import ToolSpec
from molsim_agent.science.models import ParameterValue, ScientificPlan


def prepare_lammps_md_inputs(
    workspace: Workspace,
    source: str = "POSCAR",
    temperature_K: float = 300.0,
    duration_ps: float = 1.0,
    timestep_fs: float = 1.0,
    ensemble: str = "nvt",
    overwrite: bool = False,
) -> dict[str, object]:
    if temperature_K <= 0 or duration_ps <= 0 or timestep_fs <= 0:
        raise ValueError("temperature, duration, and timestep must be positive")
    if ensemble.lower() not in {"nvt", "nve"}:
        raise ValueError("ensemble must be nvt or nve")
    steps = round(duration_ps * 1000.0 / timestep_fs)
    data_name = f"{source.rsplit('/', 1)[-1]}.data"
    data = convert_structure(workspace, source, data_name, "lammps-data", overwrite=overwrite)
    script_path = workspace.resolve("in.molsim", must_exist=False)
    if script_path.exists() and not overwrite:
        raise FileExistsError("Refusing to overwrite existing in.molsim; authorize overwrite explicitly")
    fix_line = (
        f"fix                  integrator all nvt temp {temperature_K:g} {temperature_K:g} 100.0"
        if ensemble.lower() == "nvt"
        else "fix                  integrator all nve"
    )
    script_path.write_text(f"""# Generated by molsim-agent; review before production use
clear
units                metal
atom_style           atomic
boundary             p p p
read_data            {data['destination']}

# REQUIRED USER REVIEW: pair_style, pair_coeff, masses, and any long-range settings.
# No force field or ML potential can be inferred from POSCAR.
pair_style           __REQUIRED__
pair_coeff           * * __REQUIRED__
velocity             all create {temperature_K:g} 12345 mom yes rot yes dist gaussian
timestep             {timestep_fs:g}
{fix_line}
thermo               100
thermo_style         custom step temp pe ke etotal
dump                 trajectory all custom 100 trajectory.lammpstrj id type x y z vx vy vz
run                  {steps}
""")
    plan = ScientificPlan(
        task="LAMMPS MD input preparation", code="lammps",
        parameters=[
            ParameterValue("temperature_K", temperature_K, "default" if temperature_K == 300 else "user", True),
            ParameterValue("duration_ps", duration_ps, "default" if duration_ps == 1 else "user", True),
            ParameterValue("timestep_fs", timestep_fs, "default" if timestep_fs == 1 else "user", True),
            ParameterValue("ensemble", ensemble.lower(), "default", True),
            ParameterValue("steps", steps, "derived", True),
        ],
        missing_inputs=["pair_style", "pair_coeff", "force-field or ML potential", "validated masses", "LAMMPS executable"],
        artifacts=[str(data["destination"]), "in.molsim"],
    )
    return {
        "ok": True, "created_files": list(data.get("created_files", [])) + ["in.molsim"],
        "destination": data["destination"], "scientific_plan": plan.to_dict(),
        "warnings": list(data.get("warnings", [])) + [
            "LAMMPS input contains explicit __REQUIRED__ force-field placeholders.",
            "Do not run until pair_style/pair_coeff and masses are supplied and reviewed.",
        ],
    }


def lammps_tool_specs(workspace: Workspace) -> list[ToolSpec]:
    schema = {
        "type": "object", "properties": {
            "source": {"type": "string"}, "temperature_K": {"type": "number"},
            "duration_ps": {"type": "number"}, "timestep_fs": {"type": "number"},
            "ensemble": {"type": "string", "enum": ["nvt", "nve"]}, "overwrite": {"type": "boolean"},
        }, "required": ["source"], "additionalProperties": False,
    }
    return [ToolSpec(
        "prepare_lammps_md_inputs",
        "Prepare a LAMMPS data file and reviewed MD input template; never invents a force field.",
        schema,
        lambda source="POSCAR", temperature_K=300.0, duration_ps=1.0, timestep_fs=1.0, ensemble="nvt", overwrite=False:
            prepare_lammps_md_inputs(workspace, source, temperature_K, duration_ps, timestep_fs, ensemble, overwrite),
        {"filesystem": "write", "workspace_only": True}, category="simulation", risk="write",
        requirements=("ase",), compute_cost="trivial", deterministic=True,
    )]
