"""Conservative VASP AIMD input preparation.

Only values implied by the request or standard protocol defaults are written. Electronic
parameters and POTCAR are never fabricated from POSCAR.
"""
from __future__ import annotations

from pathlib import Path
from molsim_agent.safety.policies import Workspace
from molsim_agent.tools.registry import ToolSpec
from molsim_agent.science.models import ParameterValue, ScientificPlan


def prepare_vasp_aimd_inputs(
    workspace: Workspace,
    source: str = "POSCAR",
    temperature_K: float = 300.0,
    duration_ps: float = 1.0,
    timestep_fs: float = 1.0,
    ensemble: str = "nvt",
    overwrite: bool = False,
) -> dict[str, object]:
    source_path = workspace.resolve(source, must_exist=True)
    if not source_path.is_file():
        raise ValueError(f"Not a file: {source}")
    if temperature_K <= 0 or duration_ps <= 0 or timestep_fs <= 0:
        raise ValueError("temperature, duration, and timestep must be positive")
    if ensemble.lower() not in {"nvt", "nve"}:
        raise ValueError("ensemble must be nvt or nve")
    steps = round(duration_ps * 1000.0 / timestep_fs)
    if steps < 1:
        raise ValueError("duration and timestep produce no MD steps")
    incar = workspace.root / "INCAR"
    kpoints = workspace.root / "KPOINTS"
    targets = [incar, kpoints]
    existing = [workspace.relative(path) for path in targets if path.exists()]
    if existing and not overwrite:
        raise FileExistsError(
            "Refusing to overwrite existing VASP inputs: " + ", ".join(existing) + ". "
            "Set overwrite=true only with explicit authorization."
        )
    thermostat_lines = (
        "SMASS = 0       # standard Nose-Hoover setting; verify equilibration"
        if ensemble.lower() == "nvt"
        else "# NVE: no thermostat parameter"
    )
    incar_text = f"""# Generated by molsim-agent; review before production use
SYSTEM = AIMD generated from {workspace.relative(source_path)}
IBRION = 0
NSW = {steps}
POTIM = {timestep_fs:g}
TEBEG = {temperature_K:g}
TEEND = {temperature_K:g}
ISIF = 2
{thermostat_lines}

# REQUIRED USER REVIEW: ENCUT, PREC, ISMEAR, SIGMA, ISPIN, MAGMOM,
# exchange-correlation functional, and convergence settings are not inferred.
# POTCAR must be supplied separately and match the POSCAR species.
LWAVE = .FALSE.
LCHARG = .FALSE.
"""
    kpoints_text = """Gamma-centered default mesh
0
Gamma
1 1 1
0 0 0
"""
    incar.write_text(incar_text)
    kpoints.write_text(kpoints_text)
    plan = ScientificPlan(
        task="VASP AIMD input preparation",
        code="vasp",
        parameters=[
            ParameterValue("IBRION", 0, "default", True, "MD mode"),
            ParameterValue("NSW", steps, "derived", True, "duration / timestep"),
            ParameterValue("POTIM_fs", timestep_fs, "user" if timestep_fs != 1.0 else "default", True),
            ParameterValue("temperature_K", temperature_K, "user" if temperature_K != 300.0 else "default", True),
            ParameterValue("ISIF", 2, "default", True, "fixed cell"),
            ParameterValue("kpoints", "Gamma 1x1x1", "default", True),
        ],
        missing_inputs=["POTCAR", "functional", "ENCUT", "spin", "electronic smearing", "VASP executable"],
        warnings=["Review all defaults before production use."],
        artifacts=[workspace.relative(incar), workspace.relative(kpoints)],
    )
    return {
        "ok": True,
        "created_files": [workspace.relative(incar), workspace.relative(kpoints)],
        "source": workspace.relative(source_path),
        "parameters": {
            "temperature_K": temperature_K,
            "duration_ps": duration_ps,
            "timestep_fs": timestep_fs,
            "steps": steps,
            "ensemble": ensemble.lower(),
        },
        "scientific_plan": plan.to_dict(),
        "warnings": [
            "INCAR and KPOINTS contain protocol defaults and require scientific review.",
            "POTCAR was not generated; provide matching licensed pseudopotentials.",
            "Electronic, spin, functional, and convergence parameters were intentionally left for user review.",
        ],
    }


def vasp_tool_specs(workspace: Workspace) -> list[ToolSpec]:
    return [
        ToolSpec(
            "prepare_vasp_aimd_inputs",
            "Write conservative INCAR and Gamma-point KPOINTS defaults for a requested VASP AIMD protocol; never creates POTCAR.",
            {
                "type": "object",
                "properties": {
                    "source": {"type": "string"}, "temperature_K": {"type": "number"},
                    "duration_ps": {"type": "number"}, "timestep_fs": {"type": "number"},
                    "ensemble": {"type": "string", "enum": ["nvt", "nve"]},
                    "overwrite": {"type": "boolean"},
                },
                "required": ["source"], "additionalProperties": False,
            },
            lambda source="POSCAR", temperature_K=300.0, duration_ps=1.0, timestep_fs=1.0, ensemble="nvt", overwrite=False:
                prepare_vasp_aimd_inputs(workspace, source, temperature_K, duration_ps, timestep_fs, ensemble, overwrite),
            {"filesystem": "write", "workspace_only": True},
            category="simulation", risk="write", requirements=("ase",), compute_cost="trivial", deterministic=True,
        )
    ]
