"""Interactive command-line interface."""

from __future__ import annotations

import argparse
import itertools
import json
import os
import sys
import threading
import time
from pathlib import Path
from typing import Any

from molsim_agent import Agent
from molsim_agent.llm.ollama import OllamaBackend, OllamaError
from molsim_agent.llm.openai_compatible import MistralBackend, OpenAICompatibleBackend, APIError
from molsim_agent.llm.anthropic import AnthropicBackend


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="molsim-agent",
        description="An educational molecular-simulation conversion agent",
    )
    parser.add_argument("--workspace", default=".", help="Allowed filesystem workspace")
    parser.add_argument(
        "--model",
        default=os.environ.get("MOLSIM_AGENT_MODEL"),
        help="Ollama model name (or set MOLSIM_AGENT_MODEL)",
    )
    parser.add_argument("--ollama-url", default="http://127.0.0.1:11434")
    parser.add_argument("--provider", choices=("ollama", "openai", "mistral", "anthropic"), default="ollama")
    parser.add_argument("--base-url", help="Optional API base URL for OpenAI-compatible providers")
    parser.add_argument("--api-key", help="API key (prefer OPENAI_API_KEY, MISTRAL_API_KEY, or ANTHROPIC_API_KEY)")
    parser.add_argument(
        "--profile",
        choices=("full", "compact", "auto"),
        default="auto",
        help="Model context profile; auto selects compact for Ollama and full otherwise",
    )
    parser.add_argument(
        "--timeout",
        type=float,
        default=120.0,
        help="Seconds allowed for each Ollama response",
    )
    parser.add_argument(
        "--think",
        action=argparse.BooleanOptionalAction,
        default=None,
        help="Enable or disable Ollama model thinking when supported",
    )
    parser.add_argument(
        "--max-iterations",
        type=int,
        default=20,
        help="Maximum LLM/tool loop iterations (default: 20)",
    )
    parser.add_argument("--verbose", action="store_true")
    parser.add_argument("--dry-run", action="store_true", help="Plan and inspect without writing files")
    parser.add_argument(
        "--progress",
        action="store_true",
        help="Show brief progress sentences generated by the LLM before tool calls",
    )
    parser.add_argument(
        "--progress-level",
        choices=("off", "brief", "detailed"),
        default=None,
        help="LLM progress verbosity; detailed includes factual observations",
    )
    parser.add_argument("prompt", nargs="*", help="Optional one-shot objective")
    return parser


class ConsoleEvents:
    def __init__(self, verbose: bool, progress: bool = False) -> None:
        self.verbose = verbose
        self.progress = progress
        self._spinner_stop: threading.Event | None = None
        self._spinner_thread: threading.Thread | None = None
        self._thinking_started: float | None = None
        self._run_started: float | None = None
        self._current_action = "Waiting for the model"

    def _start_thinking(self, action: str = "Waiting for the model") -> None:
        if not sys.stdout.isatty() or self._spinner_thread is not None:
            return
        stop = threading.Event()
        self._spinner_stop = stop
        self._current_action = action
        self._thinking_started = self._thinking_started or time.monotonic()
        self._run_started = self._run_started or self._thinking_started

        def animate() -> None:
            for dots in itertools.cycle((".", "..", "...")):
                if stop.wait(0.35):
                    return
                elapsed = time.monotonic() - (self._run_started or time.monotonic())
                print(f"\r{self._current_action}{dots} ({elapsed:.0f}s)   ", end="", flush=True)

        self._spinner_thread = threading.Thread(target=animate, daemon=True)
        self._spinner_thread.start()

    def _stop_thinking(self) -> None:
        if self._spinner_stop is not None:
            self._spinner_stop.set()
        if self._spinner_thread is not None:
            self._spinner_thread.join(timeout=1)
        if self._spinner_thread is not None and sys.stdout.isatty():
            print("\r                 \r", end="", flush=True)
        self._spinner_stop = None
        self._spinner_thread = None
        self._thinking_started = None

    def __call__(self, event: str, payload: dict[str, Any]) -> None:
        if event == "iteration":
            if payload.get("number") == 1:
                self._run_started = time.monotonic()
            if self.verbose:
                print(f"\nAgent loop iteration {payload['number']} (LLM turn):")
        elif event == "model_request":
            tools = payload.get("tools", [])
            tool_name = ""
            if tools:
                tool_name = tools[0].get("function", {}).get("name", "")
            labels = {
                "detect_file_format": "Checking the file format",
                "inspect_structure": "Inspecting the structure",
                "convert_structure": "Converting the structure",
                "validate_conversion": "Validating the conversion",
            }
            self._start_thinking(labels.get(tool_name, "Waiting for the model"))
            if self.verbose:
                print(f"[debug:model_request] {json.dumps(payload, indent=2, sort_keys=True)}")
        elif event == "model_response":
            self._stop_thinking()
            if self.progress and payload.get("content") and payload.get("tool_calls"):
                print(f"Progress: {payload['content'].strip()}")
            if self.verbose:
                print(f"[debug:model_response] {json.dumps(payload, indent=2, sort_keys=True)}")
        elif event == "tool_call":
            print(f"tool: {payload['name']}({json.dumps(payload['arguments'], sort_keys=True)})")
        elif event == "tool_result":
            observation = payload["observation"]
            if self.verbose:
                print("Observation:")
                print(json.dumps(observation, indent=2, sort_keys=True))
            else:
                print(f"Observation: {self._short_observation(observation)}")
        elif event == "completion_blocked":
            if self.verbose:
                print(f"Runtime guard: {payload['reason']}")
        elif event == "progress_required" and self.verbose:
            print("[debug] The model must announce its next action before the tool runs.")
        elif self.verbose and event in {"model_request", "model_response", "limit"}:
            print(f"[debug:{event}] {json.dumps(payload, indent=2, sort_keys=True)}")

    @staticmethod
    def _short_observation(observation: dict[str, Any]) -> str:
        if not observation.get("ok"):
            return f"tool failed ({observation.get('error')}): {observation.get('message')}"
        result = observation.get("result", {})
        details: list[str] = []
        for key in ("format", "source_format", "target_format", "atom_count", "destination"):
            if key in result:
                details.append(f"{key}={result[key]}")
        structure = result.get("structure", {}) if isinstance(result, dict) else {}
        if isinstance(structure, dict):
            if structure.get("species_counts"):
                details.append(f"species={structure['species_counts']}")
            if structure.get("pbc") is not None:
                details.append(f"pbc={structure['pbc']}")
        return "tool completed" + (" (" + ", ".join(details) + ")" if details else "")


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    if not args.model:
        print("Error: provide --model or set MOLSIM_AGENT_MODEL")
        return 2
    workspace = Path(args.workspace).resolve()
    if args.provider == "ollama":
        backend = OllamaBackend(args.model, base_url=args.ollama_url, timeout=args.timeout, think=args.think)
    elif args.provider == "openai":
        backend = OpenAICompatibleBackend(args.model, api_key=args.api_key, base_url=args.base_url or "https://api.openai.com/v1", timeout=args.timeout)
    elif args.provider == "mistral":
        backend = MistralBackend(args.model, api_key=args.api_key, base_url=args.base_url or "https://api.mistral.ai/v1", timeout=args.timeout)
    else:
        backend = AnthropicBackend(args.model, api_key=args.api_key, base_url=args.base_url or "https://api.anthropic.com", timeout=args.timeout)
    progress_enabled = args.progress_level not in (None, "off") or args.progress
    progress_level = args.progress_level or ("brief" if args.progress else "off")
    agent = Agent(
        backend=backend,
        model=args.model,
        workspace=workspace,
        max_iterations=args.max_iterations,
        event_handler=ConsoleEvents(args.verbose, progress_enabled),
        profile=args.profile,
        progress=args.progress,
        progress_level=progress_level,
        dry_run=args.dry_run,
    )
    print("Molecular Simulation Agent")
    print("Hello! I’m ready to inspect, convert, and validate molecular-simulation files.")
    print(f"Model: {args.model}")
    print(f"Workspace: {workspace}")
    if args.dry_run:
        print("Mode: dry run (no files will be written)")

    prompts = [" ".join(args.prompt)] if args.prompt else None
    try:
        while True:
            objective = prompts.pop() if prompts else input("\n> ").strip()
            if not objective:
                continue
            if objective.lower() in {"help", ":help"}:
                print("Commands: help, status, quit. Ask an English-language scientific file task.")
                continue
            if objective.lower() in {"status", ":status"}:
                print(f"Workspace: {workspace}\nModel: {args.model}\nProfile: {args.profile}")
                continue
            if objective.lower() in {"exit", "quit", ":q"}:
                return 0
            state = agent.run(objective)
            print(f"\nFinal:\n{state.final_answer}")
            if prompts is not None:
                return 0
    except (EOFError, KeyboardInterrupt):
        print()
        return 0
    except (OllamaError, APIError, ValueError) as exc:
        print(f"\nProvider error: {exc}")
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
